### ISSUE TITLE
set Error property not showing error message when step is overridden with "SfGpsDsAuNswFormStepOsN" lwc  

### ISSUE THREAD

**Issue by rajeshkeswani** [eschweitzer78/gps-design-systems-lwc#224] opened 2023-08-29 23:30 UTC
### Summary

We recently observed that SfGpsDsAuNswFormStepOsN lwc component for steps in omniscript is not showing error message when we have set Error property after the step.

When we remove this component and use standard step feature in omniscript , system shows the error message defined in set Error.

Could you please guide us here!

 

Sandbox : Winter 24

Omni studio setting: Managed Package Runtime is disabled

Omnistudio package version: 244.5

### Salesforce Org Type

Scratch Org

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eschweitzer78** [comment] 2023-08-30 07:10
Thanks Rajesh. I'll try to repro and let you know.

**Comment by eschweitzer78** [comment] 2023-08-30 22:10
Something to be aware of is that the current version of the library has a dependency on **OmniStudio 242.x with x>=11**. We've started to do preliminary testing with OmniStudio 244 but there are a few issues; have spotted one with Date and Datetime but there could be others.

**Comment by rajeshkeswani** [comment] 2023-08-31 02:24
Hi Emmanuel,

Thanks for your prompt response here!
unfortunately omni studio package got auto upgraded to 246.1 with winter '24  and I not allowing us to downgrade it.

Also yes, Lightning Web Security is enabled in our org as it was recommended by SF support rep. 

![image](https://github.com/eschweitzer78/gps-design-systems-lwc/assets/143563220/30aac98e-e3fa-4b6c-ae2f-d5922578eb6d)

Let me know the suitable time to connect so I can go through it

Regards,
Rajesh

**Comment by eschweitzer78** [comment] 2023-09-01 05:12
Hi Rajesh I hear the issue you're actually experiencing is with 246 in a preview sandbox. I'll send you an email not so we can catch up first thing Monday and share my findings.

**Comment by eschweitzer78** [comment] 2023-11-13 01:24
Hello Rajesh, I hope this finds you well. If you're okay with that I'll close this submission as won't fix since the issue is with the underlying Omnistudio. Happy to re-open and re-explore at any time though.

Also kindly note that we've posted an updated library/package for NSW DS which has been tested against Omnistudio 246.10.

**Closed** 2023-11-13 01:24 UTC
Labels: bug
